kind: pipeline
name: test

steps:
  - name: build
    image: golang:1.11
    commands:
      - make build

---
kind: pipeline
name: publish

depends_on:
  - test

trigger:
  event:
    - push
    - tag
  refs:
    - refs/heads/master
    - refs/tags/v*

steps:
  - name: build
    image: golang:1.11
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - make build-all-static

  - name: push image - arm
    image: plugins/docker
    settings:
      repo: iamthefij/dockron
      auto_tag: true
      auto_tag_suffix: linux-arm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - ARCH=arm
        - REPO=arm32v6

  - name: push image - arm64
    image: plugins/docker
    settings:
      repo: iamthefij/dockron
      auto_tag: true
      auto_tag_suffix: linux-arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - ARCH=arm
        - REPO=arm32v6

  - name: push image - amd64
    image: plugins/docker
    settings:
      repo: iamthefij/dockron
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: publish manifest
    image: plugins/manifest
    settings:
      spec: manifest.tmpl
      auto_tag: true
      ignore_missing: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
