---
kind: pipeline
name: test

steps:
  - name: test
    image: golang:1.15
    commands:
      - make test

  - name: check
    image: python:3-slim
    commands:
      - apt-get update
      - apt-get install -y --no-install-recommends make
      - pip install docker-compose pre-commit
      - make check

  - name: itest
    image: docker
    commands:
      - make itest

  - name: notify
    image: drillster/drone-email
    settings:
      host:
        from_secret: SMTP_HOST  # pragma: whitelist secret
      username:
        from_secret: SMTP_USER  # pragma: whitelist secret
      password:
        from_secret: SMTP_PASS  # pragma: whitelist secret
      from: drone@iamthefij.com
    when:
      status: [changed, failure]

---
kind: pipeline
name: publish

depends_on:
  - test

trigger:
  event:
    - push
    - tag
  refs:
    - refs/heads/master
    - refs/tags/v*

steps:
  - name: build
    image: golang:1.12
    commands:
      - make build-linux-static

  - name: push image - arm
    image: plugins/docker
    settings:
      repo: iamthefij/dockron
      auto_tag: true
      auto_tag_suffix: linux-arm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - ARCH=arm
        - REPO=arm32v7

  - name: push image - arm64
    image: plugins/docker
    settings:
      repo: iamthefij/dockron
      auto_tag: true
      auto_tag_suffix: linux-arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - ARCH=arm64
        - REPO=arm64v8

  - name: push image - amd64
    image: plugins/docker
    settings:
      repo: iamthefij/dockron
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: publish manifest
    image: plugins/manifest
    settings:
      spec: manifest.tmpl
      auto_tag: true
      ignore_missing: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
