platform: ${platform}

pipeline:
  build:
    image: golang:1.10
    pull: true
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      # - dep ensure -vendor-only
      - make build
  publish:
    image: plugins/docker:${docker_tag}
    # repo: iamthefij/dockron
    secrets:
      - docker_username
      - docker_password
    tag:
      - ${docker_tag}

matrix:
  include:
    - platform: linux/amd64
      docker_tag: latest
    # - platform: linux/arm
    #   docker_tag: linux-arm
