---
linters:
  enable:
    - errname
    - errorlint
    - exhaustive
    - gofumpt
    - goimports
    - goprintffuncname
    - misspell
    - gomnd
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - wrapcheck
    - wsl
  disable:
    - gochecknoglobals

linters-settings:
  gosec:
    excludes:
      - G204
  tagliatelle:
    case:
      rules:
        yaml: snake

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
