ARG REPO=library
FROM ${REPO}/golang:1.12-alpine AS builder

RUN apk add --no-cache git

RUN mkdir /app
WORKDIR /app

COPY ./go.mod ./go.sum /app/
RUN go mod download

COPY ./main.go /app/
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${ARCH} go build -a -installsuffix nocgo -o dockron .

FROM ${REPO}/busybox:latest
WORKDIR /root/
COPY --from=builder /app/dockron .

CMD [ "./dockron" ]
