ARG REPO=library
FROM golang:1.22-alpine AS builder

# hadolint ignore=DL3018
RUN apk add --no-cache git && \
    mkdir /app
WORKDIR /app

COPY ./go.mod ./go.sum /app/
RUN go mod download

COPY ./main.go /app/

ARG ARCH=amd64
ARG VERSION=dev
ENV CGO_ENABLED=0 GOOS=linux GOARCH=${ARCH}
RUN go build -ldflags "-X main.version=${VERSION}" -a -installsuffix nocgo -o dockron .

FROM scratch
COPY --from=builder /app/dockron /

ENTRYPOINT [ "/dockron" ]
