---
version: '3'

services:
  dockron:
    build:
      context: .
      dockerfile: ./Dockerfile.multi-stage
    command: ["-watch", "10s", "-debug"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  start_echoer:
    image: busybox:latest
    command: ["date"]
    labels:
      # Execute every minute
      - 'dockron.schedule=* * * * *'

  exec_echoer:
    image: busybox:latest
    command: sh -c "date > /out && tail -f /out"
    labels:
      # Execute every minute
      - 'dockron.date.schedule=* * * * *'
      - 'dockron.date.command=date >> /out'
