---
version: '3'

services:
  dockron:
    build:
      context: ../
      dockerfile: ./Dockerfile.multi-stage
    command: ["-watch", "10s", "-debug"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  start_echoer:
    image: busybox:latest
    command: sh -c "echo ok | tee -a /result.txt"
    volumes:
      - "./start_result.txt:/result.txt"
    labels:
      # Execute every minute
      - 'dockron.schedule=* * * * *'

  exec_echoer:
    image: busybox:latest
    command: sh -c "tail -f /result.txt"
    volumes:
      - "./exec_result.txt:/result.txt"
    labels:
      # Execute every minute
      - 'dockron.test.schedule=* * * * *'
      - 'dockron.test.command=echo ok >> /result.txt'
